// Copyright 2025 QMK -- generated source code only, font retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter-convert-font-image` with arguments:
//    format         | mono16
//    unicode_glyphs | 
//    output         | n14n
//    input          | atkinson_bold.png

#pragma once

#include <qp.h>

extern const uint32_t font_atkinson_bold_length;
extern const uint8_t  font_atkinson_bold[7691];
