// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | pal16
//    output | n14n
//    input  | logo_lg.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_logo_lg_length;
extern const uint8_t  gfx_logo_lg[3480];
